apiVersion: v1
kind: ServiceAccount
metadata:
  name: retail-app-sa
  namespace: retail-app
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/bedrock-app-role"
  labels:
    Project: karatu-2025-capstone
